### ISSUE TITLE
Load Balancer Settings

### ISSUE THREAD

**Issue by khfayzullaev** [Anchormen/elasticsearch-kubernetes#1]
Why would you open 9300 port for external usage?

https://github.com/Anchormen/elasticsearch-kubernetes/blob/ac24a608d6aea634f498669219bf8c3d6aa61f7f/kubernetes/es-lb-svc.yml#L15-L17

**Comment by msioufy** [comment]
Hi @khfayzullaev, thanks for your message and interest. This allows accessing ElasticSearch from a "transport client" (i.e. via its transport module, port 9300 ex. in a Java application). 

Some references and background information 
(1) **Transport Client:** https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/transport-client.html 
(2) **Transport vs Http/Rest clients:** https://www.elastic.co/blog/benchmarking-rest-client-transport-client 

Please let me know if that answers your question and I will close the issue after ;) 
PS: of course in scenarios where u don't need that feature (can be typically the case), u can remove these lines to disable access to :9300 from outside the cluster

**Comment by khfayzullaev** [comment]
@Siouffy, makes sense! Forgot about Java API use cases 👍
